sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx5a33b542788f65f0
    secret: 2c6eaae98717b5ce6d59aea50a6ff316